name: EAS Build and Auto-Submit to TestFlight

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Install, Build and Submit to TestFlight
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build and Submit to Apple TestFlight (iOS)
        run: eas build --platform ios --profile production --auto-submit --non-interactive
